const translations = {
  en: {
    "modal.selectLanguage": "Select Language",
    "common.backHome": "Back to home",
    "nav.features": "Features",
    "nav.howItWorks": "How It Works",
    "nav.pricing": "Pricing",
    "nav.faq": "FAQ",
    "nav.download": "Download",
    "hero.badge": "For Distinguished Individuals",
    "hero.title1": "Live the Moment,",
    "hero.title2": "With Who You Want.",
    "hero.subtitle": "Meet distinguished individuals with shared interests, plan exclusive events, and move through a privacy-first badge system that makes every connection feel intentional.",
    "hero.downloadIos": "Download on App Store",
    "hero.androidSoon": "Android rolling out soon",
    "hero.learnMore": "How It Works?",
    "hero.stats.members": "Active Members",
    "hero.stats.events": "Events",
    "hero.stats.store": "App Stores",
    "platforms.iosState": "Live now",
    "platforms.iosBody": "Apple Sign-In, App Store polish, and the original EliteLoop baseline experience.",
    "platforms.androidState": "Coming next",
    "platforms.androidBody": "Google Maps, Google Sign-In, premium badge rules, and the same product logic in Android-native form.",
    "map.cardLabel": "Exclusive event",
    "map.cardTitle": "Dinner plans?",
    "map.cardBody": "Tonight · 3 attendees · badge-aware access",
    "map.insightTitle": "4 elites in view",
    "map.insightBody": "The count follows the area you are exploring on the map.",
    "features.badge": "Features",
    "features.title": "Why EliteLoop?",
    "features.subtitle": "More than ordinary social media. Real connections, real moments, and controlled access around the map.",
    "features.privacy.title": "Privacy First",
    "features.privacy.desc": "Your location is shown approximately. Your identity is protected with the badge system.",
    "features.badges.title": "Badge System",
    "features.badges.desc": "Reflect your status with Bronze, Silver, and Gold badges. Access events matching your level.",
    "features.location.title": "Location Based",
    "features.location.desc": "See nearby events on the map. Make plans instantly, meet right away.",
    "features.chat.title": "Instant Messaging",
    "features.chat.desc": "Start chatting right when the host approves. Real-time communication.",
    "features.events.title": "Special Events",
    "features.events.desc": "Coffee, dinner, sports, travel... plan or join any activity you want.",
    "features.multilang.title": "Multi-language",
    "features.multilang.desc": "Turkish, English, Russian, Arabic, Chinese, and Japanese support. Global community.",
    "how.badge": "How It Works",
    "how.title": "Get Started in 3 Steps",
    "how.subtitle": "Create your first event or join one within minutes.",
    "how.step1.title": "Download the app",
    "how.step1.desc": "Download EliteLoop from the App Store and sign in with Apple ID. Your personal information stays secure.",
    "how.step1.cta": "Sign in with Apple",
    "how.step2.title": "Create your profile",
    "how.step2.desc": "Add your hobbies, the languages you speak, and your introduction. Choose your badge.",
    "how.step3.title": "Discover and connect",
    "how.step3.desc": "See events on the map, apply to ones you like, or create your own event.",
    "how.step3.cta": "Map discovery · event requests · live messaging",
    "pricing.badge": "Pricing",
    "pricing.title": "Choose your plan",
    "pricing.subtitle": "Try free for 3 days. Cancel anytime.",
    "pricing.free": "Free",
    "pricing.perMonth": "/month",
    "pricing.perYear": "/year",
    "pricing.popular": "Most Popular",
    "pricing.bronze.desc": "Perfect to start",
    "pricing.bronze.f1": "View Bronze events",
    "pricing.bronze.f2": "Create events",
    "pricing.bronze.f3": "Apply to events",
    "pricing.bronze.f4": "Basic profile",
    "pricing.bronze.f5": "Silver and Gold events",
    "pricing.bronze.f6": "Direct messaging",
    "pricing.silver.desc": "For active users",
    "pricing.silver.f1": "Bronze + Silver events",
    "pricing.silver.f2": "See nearby user names and locations",
    "pricing.silver.f3": "Direct messaging to anyone",
    "pricing.silver.f4": "Gold events",
    "pricing.gold.desc": "Premium experience",
    "pricing.gold.f1": "Access all Bronze, Silver and Gold events",
    "pricing.gold.f2": "See all nearby users and profile photos",
    "pricing.gold.f3": "Direct messaging to anyone",
    "pricing.gold.f4": "2 free monthly event boosts",
    "pricing.startFree": "Start Free",
    "pricing.tryFree": "Try 3 Days Free",
    "pricing.getGold": "Get Gold",
    "faq.badge": "FAQ",
    "faq.title": "Frequently asked questions",
    "faq.subtitle": "Everything you need to know about EliteLoop.",
    "faq.q1": "What is EliteLoop?",
    "faq.a1": "EliteLoop is an activity matching platform designed for distinguished individuals. It helps people meet through shared interests and special events while keeping privacy central.",
    "faq.q2": "How does the badge system work?",
    "faq.a2": "There are 3 badge levels: Bronze, Silver, and Gold. Bronze is free. Silver and Gold unlock more visibility, access, and messaging power.",
    "faq.q3": "How is privacy ensured?",
    "faq.a3": "Your location is approximate, not exact. Personal information is protected with Apple Sign-In and controlled profile sharing.",
    "faq.q4": "How can I cancel my subscription?",
    "faq.a4": "You can cancel anytime from App Store settings. Premium stays active until the end of the current billing period.",
    "faq.q5": "Which countries is it available in?",
    "faq.a5": "EliteLoop supports Turkish, English, Russian, Arabic, Chinese, and Japanese in its product direction and is designed for a global community.",
    "faq.q6": "What about Android?",
    "faq.a6": "Android should be visible as a first-class platform story, not a quiet footnote under the iPhone version.",
    "download.badge": "Download",
    "download.title": "Start now",
    "download.subtitle": "First 3 days free. Join the exclusive community with a landing experience that treats Android and iOS like one brand.",
    "download.rating": "4.9 rating",
    "download.downloads": "10,000+ downloads",
    "download.iosLabel": "Download on",
    "download.androidLabel": "Android status",
    "download.androidTitle": "Google Play rollout",
    "download.androidBody": "See how the Android track is positioned inside the same brand system.",
    "footer.desc": "Exclusive connections, special moments. Privacy-first activity matching platform.",
    "footer.product": "Product",
    "footer.legal": "Legal",
    "footer.contact": "Contact",
    "footer.support": "Support",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "footer.gdpr": "GDPR",
    "footer.rights": "All rights reserved.",
    "legal.updated": "Last updated: March 21, 2026",
    "legal.privacy.badge": "Privacy Policy",
    "legal.privacy.title": "Privacy policy designed with the same premium clarity",
    "legal.privacy.subtitle": "Understand how EliteLoop protects your data, location privacy, and account information.",
    "legal.terms.badge": "Terms of Service",
    "legal.terms.title": "Terms that match the product's premium tone",
    "legal.terms.subtitle": "Review the rules, badge access principles, and subscription conditions that govern EliteLoop.",
    "legal.gdpr.title": "GDPR clarity for a premium social product",
    "legal.gdpr.subtitle": "Review your GDPR rights, data access options, and control mechanisms inside EliteLoop.",
    "legal.support.badge": "Support",
    "legal.support.title": "Support that feels as considered as the product",
    "legal.support.subtitle": "Reach the EliteLoop team for account help, subscriptions, privacy questions, and general support.",
    "android.badge": "Android track",
    "android.title": "Android built with the same EliteLoop standards",
    "android.subtitle": "Follow the Android rollout, feature parity, and premium map-led experience as EliteLoop expands across both platforms.",
    "android.meta": "Closed testing, Google Maps parity, badge-aware access, and the same core social rules."
  },
  tr: {
    "modal.selectLanguage": "Dil Seçin",
    "common.backHome": "Anasayfaya dön",
    "nav.features": "Özellikler",
    "nav.howItWorks": "Nasıl Çalışır",
    "nav.pricing": "Fiyatlar",
    "nav.faq": "SSS",
    "nav.download": "İndir",
    "hero.badge": "Seçkin Bireyler İçin",
    "hero.title1": "İstediğin Anı,",
    "hero.title2": "İstediğin Kişiyle Yaşa.",
    "hero.subtitle": "Ortak ilgi alanlarına sahip seçkin insanlarla tanış, özel etkinlikler planla ve her bağlantıyı daha bilinçli hissettiren gizlilik öncelikli rozet sistemiyle ilerle.",
    "hero.downloadIos": "App Store'dan İndir",
    "hero.androidSoon": "Android çok yakında",
    "hero.learnMore": "Nasıl Çalışır?",
    "hero.stats.members": "Aktif Uye",
    "hero.stats.events": "Etkinlik",
    "hero.stats.store": "Uygulama Magazalari",
    "platforms.iosState": "Su an canli",
    "platforms.iosBody": "Apple Sign-In, App Store kalitesi ve EliteLoop'un orijinal temel deneyimi.",
    "platforms.androidState": "Sıradaki hat",
    "platforms.androidBody": "Google Maps, Google Sign-In, premium rozet kuralları ve aynı ürün mantığı Android doğasında.",
    "map.cardLabel": "Özel etkinlik",
    "map.cardTitle": "Akşam yemeği?",
    "map.cardBody": "Bu gece · 3 katılımcı · rozet duyarlılığı olan erişim",
    "map.insightTitle": "Görünümde 4 elite",
    "map.insightBody": "Sayı, haritada baktığın bölgeye göre değişir.",
    "features.badge": "Özellikler",
    "features.title": "Neden EliteLoop?",
    "features.subtitle": "Sıradan sosyal medyadan daha fazlası. Harita etrafında gerçek bağlantılar, gerçek anlar ve kontrollü erişim.",
    "features.privacy.title": "Gizlilik Önce",
    "features.privacy.desc": "Konumun tam değil yaklaşık gösterilir. Kimliğin rozet sistemiyle korunur.",
    "features.badges.title": "Rozet Sistemi",
    "features.badges.desc": "Bronze, Silver ve Gold rozetlerle seviyeni yansıt. Seviyene uygun etkinliklere eriş.",
    "features.location.title": "Konum Bazlı",
    "features.location.desc": "Yakındaki etkinlikleri haritada gör. Anında plan yap, hemen buluş.",
    "features.chat.title": "Anlık Mesajlaşma",
    "features.chat.desc": "Etkinlik sahibi onay verdiği anda sohbete başla. Gerçek zamanlı iletişim.",
    "features.events.title": "Özel Etkinlikler",
    "features.events.desc": "Kahve, yemek, spor, seyahat... istediğin aktiviteyi planla ya da katıl.",
    "features.multilang.title": "Çok Dilli",
    "features.multilang.desc": "Türkçe, İngilizce, Rusça, Arapça, Çince ve Japonca desteği. Global topluluk.",
    "how.badge": "Nasıl Çalışır",
    "how.title": "3 Adımda Başla",
    "how.subtitle": "Dakikalar içinde ilk etkinliğini oluştur ya da bir etkinliğe katıl.",
    "how.step1.title": "Uygulamayı indir",
    "how.step1.desc": "EliteLoop'u App Store'dan indir ve Apple ID ile giriş yap. Kişisel bilgilerin güvende kalır.",
    "how.step1.cta": "Apple ile Giriş Yap",
    "how.step2.title": "Profilini oluştur",
    "how.step2.desc": "Hobilerini, konuştuğun dilleri ve kendini tanıtan bilgileri ekle. Rozetini seç.",
    "how.step3.title": "Keşfet ve bağlan",
    "how.step3.desc": "Haritada etkinlikleri gör, ilgini çekenlere başvur ya da kendi etkinliğini oluştur.",
    "how.step3.cta": "Harita keşfi · etkinlik talepleri · canlı mesajlaşma",
    "pricing.badge": "Fiyatlar",
    "pricing.title": "Planını seç",
    "pricing.subtitle": "İlk 3 gün ücretsiz dene. İstediğin zaman iptal et.",
    "pricing.free": "Ücretsiz",
    "pricing.perMonth": "/ay",
    "pricing.perYear": "/yıl",
    "pricing.popular": "En Popüler",
    "pricing.bronze.desc": "Başlangıç için ideal",
    "pricing.bronze.f1": "Bronze etkinlikleri gör",
    "pricing.bronze.f2": "Etkinlik oluştur",
    "pricing.bronze.f3": "Etkinliklere başvur",
    "pricing.bronze.f4": "Temel profil",
    "pricing.bronze.f5": "Silver ve Gold etkinlikler",
    "pricing.bronze.f6": "Direkt mesajlaşma",
    "pricing.silver.desc": "Aktif kullanıcılar için",
    "pricing.silver.f1": "Bronze + Silver etkinlikleri",
    "pricing.silver.f2": "Yakındaki kullanıcı isim ve konumları",
    "pricing.silver.f3": "Herkese direkt mesaj",
    "pricing.silver.f4": "Gold etkinlikler",
    "pricing.gold.desc": "Premium deneyim",
    "pricing.gold.f1": "Tüm Bronze, Silver ve Gold etkinlikler",
    "pricing.gold.f2": "Tüm yakındaki kullanıcılar ve profil fotoğrafları",
    "pricing.gold.f3": "Herkese direkt mesaj",
    "pricing.gold.f4": "Ayda 2 ücretsiz etkinlik öne çıkarma",
    "pricing.startFree": "Ücretsiz Başla",
    "pricing.tryFree": "3 Gün Ücretsiz Dene",
    "pricing.getGold": "Gold Ol",
    "faq.badge": "SSS",
    "faq.title": "Sıkça sorulan sorular",
    "faq.subtitle": "EliteLoop hakkında bilmen gereken her şey.",
    "faq.q1": "EliteLoop nedir?",
    "faq.a1": "EliteLoop, seçkin bireyler için tasarlanmış bir aktivite eşleştirme platformudur. Ortak ilgiler ve özel etkinlikler üzerinden insanları bir araya getirirken gizliliği merkezde tutar.",
    "faq.q2": "Rozet sistemi nasıl çalışır?",
    "faq.a2": "3 rozet seviyesi vardır: Bronze, Silver ve Gold. Bronze ücretsizdir. Silver ve Gold daha fazla görünürlük, erişim ve mesajlaşma gücü açar.",
    "faq.q3": "Gizlilik nasıl sağlanır?",
    "faq.a3": "Konumun tam değil yaklaşık gösterilir. Kişisel bilgiler Apple Sign-In ve kontrollü profil paylaşımı ile korunur.",
    "faq.q4": "Aboneliği nasıl iptal ederim?",
    "faq.a4": "App Store ayarlarından istediğin an iptal edebilirsin. Premium özellikler mevcut faturalama dönemi bitene kadar aktif kalır.",
    "faq.q5": "Hangi ülkelerde kullanılabilir?",
    "faq.a5": "EliteLoop ürün yönünde Türkçe, İngilizce, Rusça, Arapça, Çince ve Japonca destekler ve global bir topluluk için tasarlanır.",
    "faq.q6": "Android ne durumda?",
    "faq.a6": "Android, iPhone sürümünün altına saklanmış bir not gibi değil, birinci sınıf platform hikayesi olarak görünmeli.",
    "download.badge": "İndir",
    "download.title": "Şimdi başla",
    "download.subtitle": "İlk 3 gün ücretsiz. Android ve iOS'u tek marka gibi anlatan seçkin topluluğa katıl.",
    "download.rating": "4.9 puan",
    "download.downloads": "10.000+ indirme",
    "download.iosLabel": "Buradan indir",
    "download.androidLabel": "Android durumu",
    "download.androidTitle": "Google Play dağıtımı",
    "download.androidBody": "Android hattının aynı marka sistemi içinde nasıl konumlandığını gör.",
    "footer.desc": "Seçkin bağlantılar, özel anlar. Gizlilik önceleyen aktivite eşleştirme platformu.",
    "footer.product": "Ürün",
    "footer.legal": "Yasal",
    "footer.contact": "İletişim",
    "footer.support": "Destek",
    "footer.privacy": "Gizlilik Politikası",
    "footer.terms": "Kullanım Koşulları",
    "footer.gdpr": "GDPR",
    "footer.rights": "Tüm hakları saklıdır.",
    "legal.updated": "Son güncelleme: 21 Mart 2026",
    "legal.privacy.badge": "Gizlilik Politikası",
    "legal.privacy.title": "Aynı premium netlikle tasarlanmış gizlilik politikası",
    "legal.privacy.subtitle": "EliteLoop'un verilerini, konum gizliliğini ve hesap bilgilerini nasıl koruduğunu incele.",
    "legal.terms.badge": "Kullanım Koşulları",
    "legal.terms.title": "Ürünün premium tonuna uyan koşullar",
    "legal.terms.subtitle": "EliteLoop'u yöneten kuralları, rozet erişim mantığını ve abonelik koşullarını incele.",
    "legal.gdpr.title": "Premium sosyal ürün için GDPR netliği",
    "legal.gdpr.subtitle": "GDPR haklarını, veri erişim seçeneklerini ve EliteLoop içindeki kontrol mekanizmalarını incele.",
    "legal.support.badge": "Destek",
    "legal.support.title": "Ürün kadar özenli hissettiren destek yüzü",
    "legal.support.subtitle": "Hesap yardımı, abonelik, gizlilik soruları ve genel destek için EliteLoop ekibine ulaş.",
    "android.badge": "Android hattı",
    "android.title": "Android de aynı EliteLoop standartlarıyla hazırlanıyor",
    "android.subtitle": "EliteLoop iki platformda da büyürken Android rollout'unu, özellik eşleniğini ve premium harita deneyimini takip et.",
    "android.meta": "Kapalı test, Google Maps eşleniği, rozet duyarlılığı olan erişim ve aynı temel sosyal kurallar."
  },
  ru: {
    "modal.selectLanguage": "Выберите язык",
    "common.backHome": "Назад на главную",
    "nav.features": "Возможности",
    "nav.howItWorks": "Как это работает",
    "nav.pricing": "Цены",
    "nav.faq": "FAQ",
    "nav.download": "Скачать",
    "hero.badge": "Для избранных людей",
    "hero.title1": "Живи моментом,",
    "hero.title2": "с кем хочешь.",
    "hero.subtitle": "Знакомься с особенными людьми по общим интересам, планируй эксклюзивные события и двигайся через badge-систему, где приватность стоит на первом месте.",
    "hero.downloadIos": "Скачать в App Store",
    "hero.androidSoon": "Android скоро",
    "hero.learnMore": "Как это работает?",
    "hero.stats.members": "Активных участников",
    "hero.stats.events": "Событий",
    "hero.stats.store": "Магазины приложений",
    "platforms.iosState": "Уже доступно",
    "platforms.iosBody": "Apple Sign-In, качество App Store и оригинальный базовый опыт EliteLoop.",
    "platforms.androidState": "Следующий этап",
    "platforms.androidBody": "Google Maps, Google Sign-In, premium правила badge и та же продуктовая логика в Android-форме.",
    "map.cardLabel": "Эксклюзивное событие",
    "map.cardTitle": "Планы на ужин?",
    "map.cardBody": "Сегодня вечером · 3 участника · доступ по badge-правилам",
    "map.insightTitle": "4 elites в зоне",
    "map.insightBody": "Счёт следует за областью, которую ты смотришь на карте.",
    "features.badge": "Возможности",
    "features.title": "Почему EliteLoop?",
    "features.subtitle": "Больше, чем обычная соцсеть. Настоящие связи, реальные моменты и контролируемый доступ вокруг карты.",
    "features.privacy.title": "Приватность прежде всего",
    "features.privacy.desc": "Ваше местоположение показывается примерно. Ваша идентичность защищена badge-системой.",
    "features.badges.title": "Badge-система",
    "features.badges.desc": "Показывайте свой статус с Bronze, Silver и Gold. Получайте доступ к событиям по уровню.",
    "features.location.title": "На основе локации",
    "features.location.desc": "Смотрите ближайшие события на карте. Стройте планы и встречайтесь сразу.",
    "features.chat.title": "Мгновенные сообщения",
    "features.chat.desc": "Начинайте чат, как только хозяин одобрит. Настоящая работа в реальном времени.",
    "features.events.title": "Особые события",
    "features.events.desc": "Кофе, ужин, спорт, путешествия... планируйте или присоединяйтесь к тому, что хотите.",
    "features.multilang.title": "Многоязычность",
    "features.multilang.desc": "Турецкий, английский, русский, арабский, китайский и японский. Глобальное сообщество.",
    "how.badge": "Как это работает",
    "how.title": "Начните за 3 шага",
    "how.subtitle": "Создайте первое событие или присоединяйтесь к одному за пару минут.",
    "how.step1.title": "Скачайте приложение",
    "how.step1.desc": "Скачайте EliteLoop из App Store и войдите через Apple ID. Ваши личные данные остаются в безопасности.",
    "how.step1.cta": "Войти через Apple",
    "how.step2.title": "Создайте профиль",
    "how.step2.desc": "Добавьте хобби, языки и краткое представление о себе. Выберите свой badge.",
    "how.step3.title": "Открывай и общайся",
    "how.step3.desc": "Смотрите события на карте, отправляйте заявки или создайте собственное событие.",
    "how.step3.cta": "Карта · заявки · живые сообщения",
    "pricing.badge": "Цены",
    "pricing.title": "Выберите план",
    "pricing.subtitle": "Попробуйте 3 дня бесплатно. Можно отменить в любой момент.",
    "pricing.free": "Бесплатно",
    "pricing.perMonth": "/mes",
    "pricing.perYear": "/god",
    "pricing.popular": "Самый популярный",
    "pricing.bronze.desc": "Идеально для старта",
    "pricing.bronze.f1": "Просмотр Bronze-событий",
    "pricing.bronze.f2": "Создание событий",
    "pricing.bronze.f3": "Заявки на события",
    "pricing.bronze.f4": "Базовый профиль",
    "pricing.bronze.f5": "Silver i Gold sobytiya",
    "pricing.bronze.f6": "Lichnye soobshcheniya",
    "pricing.silver.desc": "Для активных пользователей",
    "pricing.silver.f1": "Bronze + Silver события",
    "pricing.silver.f2": "Имена и локации ближайших пользователей",
    "pricing.silver.f3": "Прямые сообщения любому",
    "pricing.silver.f4": "Gold sobytiya",
    "pricing.gold.desc": "Премиум-опыт",
    "pricing.gold.f1": "Доступ ко всем Bronze, Silver и Gold событиям",
    "pricing.gold.f2": "Все ближние пользователи и фото профилей",
    "pricing.gold.f3": "Прямые сообщения любому",
    "pricing.gold.f4": "2 бесплатных усиления событий в месяц",
    "pricing.startFree": "Начать бесплатно",
    "pricing.tryFree": "3 дня бесплатно",
    "pricing.getGold": "Выбрать Gold",
    "faq.badge": "FAQ",
    "faq.title": "Часто задаваемые вопросы",
    "faq.subtitle": "Все, что нужно знать о EliteLoop.",
    "faq.q1": "Что такое EliteLoop?",
    "faq.a1": "EliteLoop — платформа для подбора активностей для избранных людей. Она помогает знакомиться через общие интересы и особые события, сохраняя приватность в центре продукта.",
    "faq.q2": "Как работает badge-система?",
    "faq.a2": "Существуют 3 уровня: Bronze, Silver и Gold. Bronze бесплатен. Silver и Gold открывают больше видимости, доступа и возможностей для переписки.",
    "faq.q3": "Как обеспечивается приватность?",
    "faq.a3": "Ваше местоположение показывается не точно, а примерно. Личные данные защищены Apple Sign-In и управляемым отображением профиля.",
    "faq.q4": "Как отменить подписку?",
    "faq.a4": "Вы можете отменить подписку в настройках App Store в любой момент. Premium останется активным до конца текущего периода.",
    "faq.q5": "В каких странах доступно?",
    "faq.a5": "EliteLoop ориентируется на глобальное сообщество и поддерживает турецкий, английский, русский, арабский, китайский и японский языки.",
    "faq.q6": "А что с Android?",
    "faq.a6": "Android должен быть видим как полноценная платформа, а не как скрытое примечание под версией для iPhone.",
    "download.badge": "Скачать",
    "download.title": "Начните сейчас",
    "download.subtitle": "Первые 3 дня бесплатно. Присоединяйтесь к эксклюзивному сообществу с landing page, где Android и iOS рассказываются как один бренд.",
    "download.rating": "рейтинг 4.9",
    "download.downloads": "10 000+ загрузок",
    "download.iosLabel": "Скачать в",
    "download.androidLabel": "Статус Android",
    "download.androidTitle": "Google Play rollout",
    "download.androidBody": "Посмотрите, как Android-ветка вписана в единый бренд.",
    "footer.desc": "Эксклюзивные связи, особые моменты. Платформа подбора активностей с приватностью на первом месте.",
    "footer.product": "Продукт",
    "footer.legal": "Правовая информация",
    "footer.contact": "Контакт",
    "footer.support": "Поддержка",
    "footer.privacy": "Политика конфиденциальности",
    "footer.terms": "Условия использования",
    "footer.gdpr": "GDPR",
    "footer.rights": "Все права защищены.",
    "legal.updated": "Последнее обновление: 21 марта 2026",
    "legal.privacy.badge": "Политика конфиденциальности",
    "legal.privacy.title": "Политика конфиденциальности с тем же premium-уровнем ясности",
    "legal.privacy.subtitle": "Узнайте, как EliteLoop защищает ваши данные, приватность местоположения и данные аккаунта.",
    "legal.terms.badge": "Условия использования",
    "legal.terms.title": "Условия, соответствующие premium тону продукта",
    "legal.terms.subtitle": "Ознакомьтесь с правилами, принципами badge-доступа и условиями подписки, которые действуют в EliteLoop.",
    "legal.gdpr.title": "GDPR-ясность для premium социального продукта",
    "legal.gdpr.subtitle": "Ознакомьтесь со своими правами GDPR, возможностями доступа к данным и механизмами контроля внутри EliteLoop.",
    "legal.support.badge": "Поддержка",
    "legal.support.title": "Поддержка, оформленная так же внимательно, как и сам продукт",
    "legal.support.subtitle": "Свяжитесь с командой EliteLoop по вопросам аккаунта, подписки, приватности и общей поддержки.",
    "android.badge": "Android-ветка",
    "android.title": "Android создаётся по тем же стандартам EliteLoop",
    "android.subtitle": "Следите за rollout Android, паритетом функций и premium-опытом с картой, пока EliteLoop расширяется на обе платформы.",
    "android.meta": "Закрытое тестирование, паритет с Google Maps, доступ через badge-правила и те же базовые социальные правила."
  },
  ar: {
    "modal.selectLanguage": "اختر اللغة",
    "common.backHome": "العودة إلى الرئيسية",
    "nav.features": "المزايا",
    "nav.howItWorks": "كيف يعمل",
    "nav.pricing": "الاسعار",
    "nav.faq": "الاسئلة",
    "nav.download": "تنزيل",
    "hero.badge": "للاشخاص المميزين",
    "hero.title1": "عش اللحظة،",
    "hero.title2": "مع من تريد.",
    "hero.subtitle": "تعرّف على اشخاص مميزين يشاركونك الاهتمامات، خطط لاحداث خاصة، وتحرك داخل نظام شارات يضع الخصوصية اولا ويجعل كل تواصل مقصودا.",
    "hero.downloadIos": "تنزيل من App Store",
    "hero.androidSoon": "اندرويد قريبا",
    "hero.learnMore": "كيف يعمل؟",
    "hero.stats.members": "اعضاء نشطون",
    "hero.stats.events": "فعاليات",
    "hero.stats.store": "متاجر التطبيقات",
    "platforms.iosState": "متاح الآن",
    "platforms.iosBody": "تسجيل الدخول عبر Apple وتجربة App Store المصقولة والخط الاساسي الاصلي لـ EliteLoop.",
    "platforms.androidState": "المرحلة التالية",
    "platforms.androidBody": "Google Maps وGoogle Sign-In وقواعد الشارات المميزة والمنطق نفسه داخل صيغة اندرويد الطبيعية.",
    "map.cardLabel": "فعالية خاصة",
    "map.cardTitle": "خطط عشاء؟",
    "map.cardBody": "هذه الليلة · 3 مشاركين · وصول يعتمد على الشارات",
    "map.insightTitle": "4 نخب ضمن المشهد",
    "map.insightBody": "العدد يتبع المنطقة التي تستكشفها على الخريطة.",
    "features.badge": "المزايا",
    "features.title": "لماذا EliteLoop؟",
    "features.subtitle": "اكثر من شبكة اجتماعية عادية. علاقات حقيقية ولحظات حقيقية ووصول مضبوط حول الخريطة.",
    "features.privacy.title": "الخصوصية اولا",
    "features.privacy.desc": "يظهر موقعك بشكل تقريبي. وتحمي هويتك منظومة الشارات.",
    "features.badges.title": "نظام الشارات",
    "features.badges.desc": "اعكس مستواك عبر Bronze وSilver وGold. وادخل الى الفعاليات المناسبة لمستواك.",
    "features.location.title": "قائم على الموقع",
    "features.location.desc": "شاهد الفعاليات القريبة على الخريطة. خطط فورا والتق مباشرة.",
    "features.chat.title": "مراسلة فورية",
    "features.chat.desc": "ابدأ الدردشة بمجرد موافقة المضيف. تواصل في الوقت الحقيقي.",
    "features.events.title": "فعاليات خاصة",
    "features.events.desc": "قهوة، عشاء، رياضة، سفر... خطط لما تريد او انضم اليه.",
    "features.multilang.title": "متعدد اللغات",
    "features.multilang.desc": "دعم للتركية والانجليزية والروسية والعربية والصينية واليابانية. مجتمع عالمي.",
    "how.badge": "كيف يعمل",
    "how.title": "ابدأ في 3 خطوات",
    "how.subtitle": "أنشئ فعاليتك الاولى او انضم خلال دقائق.",
    "how.step1.title": "نزّل التطبيق",
    "how.step1.desc": "نزّل EliteLoop من App Store وسجّل عبر Apple ID. تبقى معلوماتك الشخصية آمنة.",
    "how.step1.cta": "تسجيل عبر Apple",
    "how.step2.title": "أنشئ ملفك الشخصي",
    "how.step2.desc": "أضف اهتماماتك واللغات التي تتحدثها وتقديمك الشخصي. اختر شارتك.",
    "how.step3.title": "اكتشف وتواصل",
    "how.step3.desc": "شاهد الفعاليات على الخريطة، وقدم على ما يعجبك، او أنشئ فعاليتك الخاصة.",
    "how.step3.cta": "اكتشاف الخريطة · طلبات الفعاليات · رسائل حية",
    "pricing.badge": "الاسعار",
    "pricing.title": "اختر خطتك",
    "pricing.subtitle": "جرّب مجانا 3 ايام. ويمكنك الالغاء في اي وقت.",
    "pricing.free": "مجاني",
    "pricing.perMonth": "/شهريا",
    "pricing.perYear": "/سنويا",
    "pricing.popular": "الاكثر شيوعا",
    "pricing.bronze.desc": "مثالي للبداية",
    "pricing.bronze.f1": "مشاهدة فعاليات Bronze",
    "pricing.bronze.f2": "إنشاء فعاليات",
    "pricing.bronze.f3": "التقديم على الفعاليات",
    "pricing.bronze.f4": "ملف شخصي اساسي",
    "pricing.bronze.f5": "فعاليات Silver وGold",
    "pricing.bronze.f6": "مراسلة مباشرة",
    "pricing.silver.desc": "للمستخدمين النشطين",
    "pricing.silver.f1": "فعاليات Bronze وSilver",
    "pricing.silver.f2": "رؤية اسماء ومواقع المستخدمين القريبين",
    "pricing.silver.f3": "مراسلة مباشرة لأي شخص",
    "pricing.silver.f4": "فعاليات Gold",
    "pricing.gold.desc": "تجربة فاخرة",
    "pricing.gold.f1": "وصول الى جميع فعاليات Bronze وSilver وGold",
    "pricing.gold.f2": "رؤية جميع المستخدمين القريبين وصورهم",
    "pricing.gold.f3": "مراسلة مباشرة لأي شخص",
    "pricing.gold.f4": "تعزيزان مجانيان للفعالية شهريا",
    "pricing.startFree": "ابدأ مجانا",
    "pricing.tryFree": "جرّب 3 ايام مجانا",
    "pricing.getGold": "احصل على Gold",
    "faq.badge": "الاسئلة",
    "faq.title": "الاسئلة الشائعة",
    "faq.subtitle": "كل ما تحتاج معرفته عن EliteLoop.",
    "faq.q1": "ما هو EliteLoop؟",
    "faq.a1": "EliteLoop منصة لمطابقة النشاطات صممت للاشخاص المميزين. تساعد الناس على اللقاء عبر الاهتمامات المشتركة والفعاليات الخاصة مع إبقاء الخصوصية في قلب التجربة.",
    "faq.q2": "كيف يعمل نظام الشارات؟",
    "faq.a2": "هناك 3 مستويات: Bronze وSilver وGold. Bronze مجاني. أما Silver وGold فيفتحان مزيدا من الظهور والوصول والرسائل.",
    "faq.q3": "كيف يتم ضمان الخصوصية؟",
    "faq.a3": "يظهر موقعك بشكل تقريبي لا دقيق. وتحمي البيانات الشخصية Apple Sign-In وعرض الملف الشخصي الخاضع للتحكم.",
    "faq.q4": "كيف ألغي الاشتراك؟",
    "faq.a4": "يمكنك الإلغاء في أي وقت من إعدادات App Store. تبقى المزايا المميزة فعالة حتى نهاية الفترة الحالية.",
    "faq.q5": "في أي دول يتوفر؟",
    "faq.a5": "EliteLoop موجّه لمجتمع عالمي ويدعم التركية والانجليزية والروسية والعربية والصينية واليابانية في اتجاه المنتج.",
    "faq.q6": "وماذا عن Android؟",
    "faq.a6": "يجب أن يظهر Android كمسار أساسي كامل لا كملاحظة صغيرة أسفل نسخة iPhone.",
    "download.badge": "تنزيل",
    "download.title": "ابدأ الآن",
    "download.subtitle": "اول 3 ايام مجانا. انضم الى المجتمع الحصري مع صفحة تقدم Android وiOS كعلامة واحدة.",
    "download.rating": "تقييم 4.9",
    "download.downloads": "+10,000 تنزيل",
    "download.iosLabel": "تنزيل من",
    "download.androidLabel": "حالة Android",
    "download.androidTitle": "إطلاق Google Play",
    "download.androidBody": "شاهد كيف يتم وضع مسار Android داخل النظام البصري نفسه للعلامة.",
    "footer.desc": "روابط حصرية ولحظات خاصة. منصة مطابقة نشاطات تضع الخصوصية اولا.",
    "footer.product": "المنتج",
    "footer.legal": "القانوني",
    "footer.contact": "التواصل",
    "footer.support": "الدعم",
    "footer.privacy": "سياسة الخصوصية",
    "footer.terms": "شروط الخدمة",
    "footer.gdpr": "GDPR",
    "footer.rights": "جميع الحقوق محفوظة.",
    "legal.updated": "آخر تحديث: 21 مارس 2026",
    "legal.privacy.badge": "سياسة الخصوصية",
    "legal.privacy.title": "سياسة خصوصية مصممة بالوضوح الفاخر نفسه",
    "legal.privacy.subtitle": "تعرّف على كيفية حماية EliteLoop لبياناتك وخصوصية موقعك ومعلومات حسابك.",
    "legal.terms.badge": "شروط الخدمة",
    "legal.terms.title": "شروط تناسب النبرة الفاخرة للمنتج",
    "legal.terms.subtitle": "راجع القواعد ومبادئ الوصول عبر الشارات وشروط الاشتراك التي تنظّم EliteLoop.",
    "legal.gdpr.title": "وضوح GDPR لمنتج اجتماعي فاخر",
    "legal.gdpr.subtitle": "راجع حقوقك في GDPR وخيارات الوصول إلى البيانات وآليات التحكم داخل EliteLoop.",
    "legal.support.badge": "الدعم",
    "legal.support.title": "دعم مصمم بعناية توازي عناية المنتج نفسه",
    "legal.support.subtitle": "تواصل مع فريق EliteLoop للمساعدة في الحساب والاشتراك والخصوصية والدعم العام.",
    "android.badge": "مسار Android",
    "android.title": "يتم بناء Android وفق معايير EliteLoop نفسها",
    "android.subtitle": "تابع طرح Android وتكافؤ الميزات وتجربة الخريطة الفاخرة بينما يتوسع EliteLoop عبر المنصتين.",
    "android.meta": "اختبار مغلق، تكافؤ Google Maps، وصول يعتمد على الشارات، والمنطق الاجتماعي نفسه."
  },
  zh: {
    "modal.selectLanguage": "选择语言",
    "common.backHome": "返回首页",
    "nav.features": "功能",
    "nav.howItWorks": "使用方式",
    "nav.pricing": "价格",
    "nav.faq": "常见问题",
    "nav.download": "下载",
    "hero.badge": "为高品质社交而生",
    "hero.title1": "活在此刻，",
    "hero.title2": "和你想见的人一起。",
    "hero.subtitle": "与拥有共同兴趣的优质用户相遇，策划专属活动，并通过以隐私为先的徽章体系建立更有意图的连接。",
    "hero.downloadIos": "在 App Store 下载",
    "hero.androidSoon": "Android 即将到来",
    "hero.learnMore": "如何运作？",
    "hero.stats.members": "活跃成员",
    "hero.stats.events": "活动",
    "hero.stats.store": "应用商店",
    "platforms.iosState": "现已上线",
    "platforms.iosBody": "Apple Sign-In、App Store 级打磨，以及 EliteLoop 原始基线体验。",
    "platforms.androidState": "下一阶段",
    "platforms.androidBody": "Google Maps、Google Sign-In、高级徽章规则，以及相同产品逻辑的 Android 原生版本。",
    "map.cardLabel": "专属活动",
    "map.cardTitle": "今晚晚餐？",
    "map.cardBody": "今晚 · 3 位参与者 · 按徽章级别访问",
    "map.insightTitle": "当前视野内 4 位 elites",
    "map.insightBody": "数字会跟随你正在查看的地图区域变化。",
    "features.badge": "功能",
    "features.title": "为什么选择 EliteLoop？",
    "features.subtitle": "不只是普通社交。围绕地图的真实连接、真实时刻与受控访问。",
    "features.privacy.title": "隐私优先",
    "features.privacy.desc": "你的定位以大致范围显示。你的身份由徽章体系保护。",
    "features.badges.title": "徽章体系",
    "features.badges.desc": "通过 Bronze、Silver、Gold 展示你的等级，并进入匹配等级的活动。",
    "features.location.title": "基于位置",
    "features.location.desc": "在地图上查看附近活动。即时制定计划，马上见面。",
    "features.chat.title": "即时消息",
    "features.chat.desc": "活动主理人批准后立刻开始聊天。真正实时沟通。",
    "features.events.title": "特别活动",
    "features.events.desc": "咖啡、晚餐、运动、旅行……计划你想要的活动或加入你喜欢的活动。",
    "features.multilang.title": "多语言支持",
    "features.multilang.desc": "支持土耳其语、英语、俄语、阿拉伯语、中文和日语。全球社区。",
    "how.badge": "使用方式",
    "how.title": "3 步开始",
    "how.subtitle": "几分钟内创建你的第一个活动或加入一场活动。",
    "how.step1.title": "下载应用",
    "how.step1.desc": "从 App Store 下载 EliteLoop，并通过 Apple ID 登录。你的个人信息保持安全。",
    "how.step1.cta": "使用 Apple 登录",
    "how.step2.title": "创建个人资料",
    "how.step2.desc": "添加你的兴趣、会说的语言和个人介绍，然后选择你的徽章等级。",
    "how.step3.title": "发现并连接",
    "how.step3.desc": "在地图上查看活动，申请你喜欢的活动，或创建你自己的活动。",
    "how.step3.cta": "地图探索 · 活动申请 · 实时消息",
    "pricing.badge": "价格",
    "pricing.title": "选择你的方案",
    "pricing.subtitle": "免费试用 3 天，随时取消。",
    "pricing.free": "免费",
    "pricing.perMonth": "/月",
    "pricing.perYear": "/年",
    "pricing.popular": "最受欢迎",
    "pricing.bronze.desc": "适合开始",
    "pricing.bronze.f1": "查看 Bronze 活动",
    "pricing.bronze.f2": "创建活动",
    "pricing.bronze.f3": "申请活动",
    "pricing.bronze.f4": "基础资料",
    "pricing.bronze.f5": "Silver 和 Gold 活动",
    "pricing.bronze.f6": "私信功能",
    "pricing.silver.desc": "适合活跃用户",
    "pricing.silver.f1": "Bronze + Silver 活动",
    "pricing.silver.f2": "查看附近用户姓名和位置",
    "pricing.silver.f3": "给任何人发送私信",
    "pricing.silver.f4": "Gold 活动",
    "pricing.gold.desc": "高级体验",
    "pricing.gold.f1": "访问所有 Bronze、Silver 和 Gold 活动",
    "pricing.gold.f2": "查看所有附近用户和头像",
    "pricing.gold.f3": "给任何人发送私信",
    "pricing.gold.f4": "每月 2 次免费活动加速",
    "pricing.startFree": "免费开始",
    "pricing.tryFree": "免费试用 3 天",
    "pricing.getGold": "获取 Gold",
    "faq.badge": "常见问题",
    "faq.title": "常见问题",
    "faq.subtitle": "关于 EliteLoop 你需要知道的一切。",
    "faq.q1": "什么是 EliteLoop？",
    "faq.a1": "EliteLoop 是为高品质人群设计的活动匹配平台。它通过共同兴趣和特别活动帮助人们相遇，同时将隐私放在核心位置。",
    "faq.q2": "徽章体系如何运作？",
    "faq.a2": "共有 Bronze、Silver、Gold 三个等级。Bronze 免费。Silver 和 Gold 解锁更多可见性、访问权限与消息能力。",
    "faq.q3": "如何保证隐私？",
    "faq.a3": "你的定位显示为大致范围而非精确位置。个人信息通过 Apple Sign-In 与受控资料展示得到保护。",
    "faq.q4": "如何取消订阅？",
    "faq.a4": "你可以在 App Store 设置中随时取消订阅。高级功能会持续到当前计费周期结束。",
    "faq.q5": "在哪些国家可用？",
    "faq.a5": "EliteLoop 面向全球社区，产品方向支持土耳其语、英语、俄语、阿拉伯语、中文和日语。",
    "faq.q6": "Android 呢？",
    "faq.a6": "Android 应该作为完整的平台故事被看见，而不是 iPhone 版本下方的一条小注释。",
    "download.badge": "下载",
    "download.title": "现在开始",
    "download.subtitle": "前三天免费。加入这个专属社区，并看到将 Android 与 iOS 作为同一品牌讲述的落地页。",
    "download.rating": "4.9 评分",
    "download.downloads": "10,000+ 下载",
    "download.iosLabel": "下载自",
    "download.androidLabel": "Android 状态",
    "download.androidTitle": "Google Play 发布节奏",
    "download.androidBody": "查看 Android 如何在同一品牌系统中被清晰呈现。",
    "footer.desc": "专属连接，特别时刻。以隐私为先的活动匹配平台。",
    "footer.product": "产品",
    "footer.legal": "法律",
    "footer.contact": "联系",
    "footer.support": "支持",
    "footer.privacy": "隐私政策",
    "footer.terms": "服务条款",
    "footer.gdpr": "GDPR",
    "footer.rights": "保留所有权利。",
    "legal.updated": "最后更新：2026 年 3 月 21 日",
    "legal.privacy.badge": "隐私政策",
    "legal.privacy.title": "以同样高级清晰度设计的隐私政策",
    "legal.privacy.subtitle": "了解 EliteLoop 如何保护你的数据、位置隐私与账户信息。",
    "legal.terms.badge": "服务条款",
    "legal.terms.title": "与产品高级气质匹配的条款",
    "legal.terms.subtitle": "查看管理 EliteLoop 的规则、徽章访问逻辑与订阅条款。",
    "legal.gdpr.title": "面向高级社交产品的 GDPR 清晰表达",
    "legal.gdpr.subtitle": "查看你的 GDPR 权利、数据访问选项以及 EliteLoop 内部的控制机制。",
    "legal.support.badge": "支持",
    "legal.support.title": "像产品本身一样被认真设计的支持页面",
    "legal.support.subtitle": "如需账户帮助、订阅、隐私问题或一般支持，请联系 EliteLoop 团队。",
    "android.badge": "Android 轨道",
    "android.title": "Android 也按照同样的 EliteLoop 标准打造",
    "android.subtitle": "在 EliteLoop 扩展到双平台的过程中，关注 Android 上线节奏、功能对齐与高级地图体验。",
    "android.meta": "封闭测试、Google Maps 对齐、基于徽章的访问，以及相同的核心社交规则。"
  },
  ja: {
    "modal.selectLanguage": "言語を選択",
    "common.backHome": "ホームへ戻る",
    "nav.features": "特徴",
    "nav.howItWorks": "使い方",
    "nav.pricing": "料金",
    "nav.faq": "FAQ",
    "nav.download": "ダウンロード",
    "hero.badge": "選ばれた人のために",
    "hero.title1": "その瞬間を、",
    "hero.title2": "望む相手と。",
    "hero.subtitle": "共通の興味を持つ特別な人と出会い、限定イベントを企画し、プライバシーを最優先にしたバッジシステムの中で意図あるつながりを築けます。",
    "hero.downloadIos": "App Store でダウンロード",
    "hero.androidSoon": "Android もまもなく",
    "hero.learnMore": "使い方を見る",
    "hero.stats.members": "アクティブ会員",
    "hero.stats.events": "イベント",
    "hero.stats.store": "アプリストア",
    "platforms.iosState": "公開中",
    "platforms.iosBody": "Apple Sign-In、App Store 品質、そして EliteLoop 本来の基準体験。",
    "platforms.androidState": "次のトラック",
    "platforms.androidBody": "Google Maps、Google Sign-In、プレミアムバッジルール、そして同じ製品ロジックを Android ネイティブで。",
    "map.cardLabel": "限定イベント",
    "map.cardTitle": "今夜ディナー？",
    "map.cardBody": "今夜 · 3人参加 · バッジに応じたアクセス",
    "map.insightTitle": "表示範囲に 4 elites",
    "map.insightBody": "この数は今見ている地図エリアに合わせて変わります。",
    "features.badge": "特徴",
    "features.title": "なぜ EliteLoop？",
    "features.subtitle": "普通のSNSではありません。地図の上で生まれる本物のつながり、本物の瞬間、そして制御されたアクセスです。",
    "features.privacy.title": "プライバシー優先",
    "features.privacy.desc": "位置情報はおおまかに表示されます。あなたの身元はバッジシステムで守られます。",
    "features.badges.title": "バッジシステム",
    "features.badges.desc": "Bronze、Silver、Gold で自分のレベルを表現し、そのレベルに合うイベントに参加できます。",
    "features.location.title": "位置情報ベース",
    "features.location.desc": "近くのイベントを地図で確認し、その場で予定を立ててすぐ会えます。",
    "features.chat.title": "リアルタイムメッセージ",
    "features.chat.desc": "主催者が承認した瞬間にチャット開始。リアルタイムで会話できます。",
    "features.events.title": "特別なイベント",
    "features.events.desc": "コーヒー、ディナー、スポーツ、旅行... 好きなアクティビティを企画または参加できます。",
    "features.multilang.title": "多言語対応",
    "features.multilang.desc": "トルコ語、英語、ロシア語、アラビア語、中国語、日本語に対応。グローバルなコミュニティです。",
    "how.badge": "使い方",
    "how.title": "3ステップで開始",
    "how.subtitle": "数分で最初のイベントを作成、または参加できます。",
    "how.step1.title": "アプリをダウンロード",
    "how.step1.desc": "App Store から EliteLoop をダウンロードし、Apple ID でログイン。個人情報は安全に保たれます。",
    "how.step1.cta": "Apple でサインイン",
    "how.step2.title": "プロフィール作成",
    "how.step2.desc": "趣味、話せる言語、自己紹介を追加し、バッジを選びます。",
    "how.step3.title": "発見してつながる",
    "how.step3.desc": "地図上でイベントを見つけ、気になるものに応募するか、自分のイベントを作成します。",
    "how.step3.cta": "地図探索 · イベント申請 · ライブメッセージ",
    "pricing.badge": "料金",
    "pricing.title": "プランを選ぶ",
    "pricing.subtitle": "3日間無料で試せます。いつでも解約可能です。",
    "pricing.free": "無料",
    "pricing.perMonth": "/月",
    "pricing.perYear": "/年",
    "pricing.popular": "人気プラン",
    "pricing.bronze.desc": "最初の一歩に最適",
    "pricing.bronze.f1": "Bronze イベントを見る",
    "pricing.bronze.f2": "イベントを作成",
    "pricing.bronze.f3": "イベントに応募",
    "pricing.bronze.f4": "基本プロフィール",
    "pricing.bronze.f5": "Silver と Gold イベント",
    "pricing.bronze.f6": "ダイレクトメッセージ",
    "pricing.silver.desc": "アクティブユーザー向け",
    "pricing.silver.f1": "Bronze + Silver イベント",
    "pricing.silver.f2": "近くのユーザー名と位置を確認",
    "pricing.silver.f3": "誰にでもダイレクトメッセージ",
    "pricing.silver.f4": "Gold イベント",
    "pricing.gold.desc": "プレミアム体験",
    "pricing.gold.f1": "すべての Bronze・Silver・Gold イベントにアクセス",
    "pricing.gold.f2": "近くの全ユーザーとプロフィール写真を見る",
    "pricing.gold.f3": "誰にでもダイレクトメッセージ",
    "pricing.gold.f4": "毎月2回の無料イベントブースト",
    "pricing.startFree": "無料で始める",
    "pricing.tryFree": "3日間無料で試す",
    "pricing.getGold": "Gold を選ぶ",
    "faq.badge": "FAQ",
    "faq.title": "よくある質問",
    "faq.subtitle": "EliteLoop について知っておきたいこと。",
    "faq.q1": "EliteLoop とは？",
    "faq.a1": "EliteLoop は選ばれた人のために設計されたアクティビティ・マッチング・プラットフォームです。共通の興味や特別なイベントを通じて出会いを生み、プライバシーを中心に置いています。",
    "faq.q2": "バッジシステムはどう動く？",
    "faq.a2": "Bronze、Silver、Gold の3段階があります。Bronze は無料で、Silver と Gold はより高い可視性、アクセス、メッセージ機能を解放します。",
    "faq.q3": "プライバシーはどう守られる？",
    "faq.a3": "位置情報は正確な地点ではなくおおまかな範囲で表示されます。個人情報は Apple Sign-In と制御されたプロフィール表示で保護されます。",
    "faq.q4": "サブスクリプションはどう解約する？",
    "faq.a4": "App Store の設定からいつでも解約できます。プレミアム機能は現在の請求期間が終わるまで有効です。",
    "faq.q5": "どの国で使える？",
    "faq.a5": "EliteLoop はグローバルなコミュニティを想定し、トルコ語、英語、ロシア語、アラビア語、中国語、日本語を製品方針としてサポートしています。",
    "faq.q6": "Android はどうなる？",
    "faq.a6": "Android も iPhone 版の下に隠れる注釈ではなく、独立した一級のプラットフォームとして見せるべきです。",
    "download.badge": "ダウンロード",
    "download.title": "今すぐ始める",
    "download.subtitle": "最初の3日間は無料。Android と iOS をひとつのブランドとして語るランディングで、特別なコミュニティに参加しましょう。",
    "download.rating": "評価 4.9",
    "download.downloads": "10,000+ ダウンロード",
    "download.iosLabel": "こちらから",
    "download.androidLabel": "Android 状況",
    "download.androidTitle": "Google Play ロールアウト",
    "download.androidBody": "Android トラックが同じブランドシステム内でどう見えるか確認できます。",
    "footer.desc": "特別なつながり、特別な瞬間。プライバシー優先のアクティビティマッチング・プラットフォーム。",
    "footer.product": "製品",
    "footer.legal": "法的情報",
    "footer.contact": "連絡先",
    "footer.support": "サポート",
    "footer.privacy": "プライバシーポリシー",
    "footer.terms": "利用規約",
    "footer.gdpr": "GDPR",
    "footer.rights": "All rights reserved.",
    "legal.updated": "最終更新: 2026年3月21日",
    "legal.privacy.badge": "プライバシーポリシー",
    "legal.privacy.title": "同じプレミアムな明快さで設計されたプライバシーポリシー",
    "legal.privacy.subtitle": "EliteLoop があなたのデータ、位置情報のプライバシー、アカウント情報をどのように保護するか確認できます。",
    "legal.terms.badge": "利用規約",
    "legal.terms.title": "製品のプレミアムな空気感に合う規約",
    "legal.terms.subtitle": "EliteLoop を利用するうえでのルール、バッジアクセスの考え方、サブスクリプション条件を確認できます。",
    "legal.gdpr.title": "プレミアムソーシャル製品のための GDPR の明確さ",
    "legal.gdpr.subtitle": "GDPR に関する権利、データアクセスの選択肢、EliteLoop 内での管理方法を確認できます。",
    "legal.support.badge": "サポート",
    "legal.support.title": "製品と同じだけ丁寧に設計されたサポート",
    "legal.support.subtitle": "アカウント、サブスクリプション、プライバシー、一般的なサポートについて EliteLoop チームに連絡できます。",
    "android.badge": "Android トラック",
    "android.title": "Android も同じ EliteLoop の基準で構築されています",
    "android.subtitle": "EliteLoop が両プラットフォームへ広がる中で、Android の展開、機能パリティ、プレミアムな地図体験を確認できます。",
    "android.meta": "クローズドテスト、Google Maps の整合、バッジに応じたアクセス、そして同じコアなソーシャルルール。"
  }
};

const legalContent = {
  privacy: {
    en: [
      ["Information we collect", "EliteLoop may collect account identity, profile details you choose to share, approximate location data, event participation data, chat metadata, and subscription state."],
      ["Why we process data", "We process data to operate the app, secure the platform, support premium badge rules, show relevant people and events, and improve moderation and service quality."],
      ["Location and visibility", "Location is treated as a privacy-sensitive signal. The product is designed around approximate visibility, badge-aware access, and user-controlled profile exposure."],
      ["Messaging and events", "Messages, event requests, participant actions, and approvals may be processed to keep chat, event participation, notifications, and safety systems working correctly."],
      ["Third-party services", "Apple, Google, RevenueCat, Supabase, Cloudinary, and infrastructure tools may process limited data where required to support authentication, subscriptions, storage, and delivery."],
      ["Your choices", "You can manage profile information, visibility, account deletion, and subscription status from the app. Privacy or data requests can be sent to info@eliteloop.app."]
    ],
    tr: [
      ["Topladığımız bilgiler", "EliteLoop; hesap kimliği, paylaşmayı seçtiğin profil bilgileri, yaklaşık konum verisi, etkinliğe katılım verisi, sohbet üstverisi ve abonelik durumunu toplayabilir."],
      ["Veriyi neden işliyoruz", "Veriyi uygulamayı çalıştırmak, platformu güvende tutmak, premium rozet kurallarını uygulamak, ilgili kişi ve etkinlikleri göstermek ve moderasyon kalitesini iyileştirmek için işleriz."],
      ["Konum ve görünürlük", "Konum gizlilik hassasiyeti olan bir sinyal olarak ele alınır. Ürün, yaklaşık görünürlük, rozet duyarlılığı olan erişim ve kullanıcı kontrollü profil görünürlüğü etrafında tasarlanmıştır."],
      ["Mesajlaşma ve etkinlikler", "Mesajlar, etkinlik talepleri, katılımcı aksiyonları ve onaylar; sohbet, etkinlik katılımı, bildirimler ve güvenlik sistemlerinin doğru çalışması için işlenebilir."],
      ["Üçüncü taraf servisler", "Apple, Google, RevenueCat, Supabase, Cloudinary ve altyapı araçları; kimlik doğrulama, abonelik, depolama ve teslim için gerekli olduğunda sınırlı veri işleyebilir."],
      ["Seçeneklerin", "Profil bilgilerini, görünürlüğü, hesap silmeyi ve abonelik durumunu uygulama içinden yönetebilirsin. Gizlilik veya veri taleplerini info@eliteloop.app adresine iletebilirsin."]
    ],
    ru: [
      ["Какие данные мы собираем", "EliteLoop может собирать данные учетной записи, данные профиля, которые вы решили показать, примерные данные о локации, участие в событиях, метаданные чата и статус подписки."],
      ["Зачем мы обрабатываем данные", "Данные обрабатываются для работы приложения, безопасности платформы, применения premium badge-правил, показа подходящих людей и событий, а также улучшения модерации и качества сервиса."],
      ["Локация и видимость", "Местоположение рассматривается как чувствительный сигнал. Продукт построен вокруг примерной видимости, badge-зависимого доступа и управляемой показанности профиля."],
      ["Сообщения и события", "Сообщения, заявки на события, действия участников и одобрения могут обрабатываться, чтобы поддерживать чат, участие в событиях, уведомления и системы безопасности."],
      ["Сторонние сервисы", "Apple, Google, RevenueCat, Supabase, Cloudinary и инструменты инфраструктуры могут обрабатывать ограниченные данные, когда это необходимо для авторизации, подписок, хранения и доставки."],
      ["Ваши возможности", "Вы можете управлять данными профиля, видимостью, удалением аккаунта и статусом подписки внутри приложения. Запросы по данным и приватности можно отправлять на info@eliteloop.app."]
    ],
    ar: [
      ["ما البيانات التي نجمعها", "قد يجمع EliteLoop بيانات الحساب، وتفاصيل الملف الشخصي التي تختار مشاركتها، وبيانات الموقع التقريبية، وبيانات المشاركة في الفعاليات، وبيانات وصفية للدردشة، وحالة الاشتراك."],
      ["لماذا نعالج البيانات", "نعالج البيانات لتشغيل التطبيق، وتأمين المنصة، وتطبيق قواعد الشارات المميزة، وإظهار الاشخاص والفعاليات المناسبة، وتحسين الاشراف وجودة الخدمة."],
      ["الموقع والظهور", "يُعامل الموقع كإشارة حساسة للخصوصية. وقد صُمم المنتج حول الظهور التقريبي، والوصول القائم على الشارات، والتحكم الذي يملكه المستخدم في ظهور ملفه الشخصي."],
      ["الرسائل والفعاليات", "قد تتم معالجة الرسائل وطلبات الفعاليات وإجراءات المشاركين والموافقات حتى تعمل الدردشة والمشاركة والاشعارات وانظمة الامان بشكل صحيح."],
      ["الخدمات الخارجية", "قد تعالج Apple وGoogle وRevenueCat وSupabase وCloudinary وبعض ادوات البنية التحتية قدرا محدودا من البيانات عند الحاجة لدعم تسجيل الدخول والاشتراكات والتخزين والتسليم."],
      ["خياراتك", "يمكنك ادارة بيانات الملف الشخصي والظهور وحذف الحساب وحالة الاشتراك من داخل التطبيق. ويمكن ارسال طلبات الخصوصية او البيانات الى info@eliteloop.app."]
    ],
    zh: [
      ["我们收集哪些信息", "EliteLoop 可能收集账户身份信息、你选择公开的资料信息、大致位置数据、活动参与数据、聊天元数据以及订阅状态。"],
      ["为什么处理这些数据", "我们处理数据是为了运行应用、保障平台安全、执行高级徽章规则、展示相关用户与活动，并提升审核与服务质量。"],
      ["位置与可见性", "位置被视为隐私敏感信号。产品围绕大致可见范围、基于徽章的访问，以及由用户控制的资料曝光而设计。"],
      ["消息与活动", "消息、活动申请、参与者操作与审批，可能会被处理，以保证聊天、活动参与、通知与安全系统正常工作。"],
      ["第三方服务", "Apple、Google、RevenueCat、Supabase、Cloudinary 以及部分基础设施工具，可能在认证、订阅、存储与交付所需的范围内处理有限数据。"],
      ["你的选择", "你可以在应用中管理个人资料、可见性、账户删除与订阅状态。隐私或数据请求可发送至 info@eliteloop.app。"]
    ],
    ja: [
      ["収集する情報", "EliteLoop は、アカウント情報、共有を選んだプロフィール情報、おおまかな位置情報、イベント参加情報、チャットのメタデータ、サブスクリプション状態を収集する場合があります。"],
      ["データを処理する理由", "アプリを運用し、プラットフォームを安全に保ち、プレミアムバッジのルールを適用し、関連する人やイベントを表示し、モデレーションとサービス品質を高めるために処理します。"],
      ["位置情報と表示", "位置情報はプライバシーに関わる重要な信号として扱われます。製品は、おおまかな可視化、バッジに応じたアクセス、ユーザーが管理するプロフィール露出を前提に設計されています。"],
      ["メッセージとイベント", "メッセージ、イベント申請、参加者の行動、承認は、チャット、イベント参加、通知、安全機能を正しく動かすために処理される場合があります。"],
      ["第三者サービス", "Apple、Google、RevenueCat、Supabase、Cloudinary、および一部のインフラツールは、認証、購読、保存、配信に必要な範囲で限定的なデータを処理することがあります。"],
      ["あなたの選択", "プロフィール情報、表示設定、アカウント削除、サブスクリプション状態はアプリ内で管理できます。プライバシーやデータに関する依頼は info@eliteloop.app へ送信できます。"]
    ]
  },
  terms: {
    en: [
      ["Using the platform", "By using EliteLoop, you agree to use the platform lawfully, respectfully, and in line with product rules around badges, events, and messaging."],
      ["Accounts and access", "Users are responsible for their sign-in credentials, account accuracy, and activity within the app. Access to some features depends on badge level or host approval."],
      ["Events and participation", "Creating, joining, approving, and messaging around events must follow product rules. Event hosts and participants are expected to act in good faith and avoid misuse."],
      ["Subscriptions", "Paid plans unlock additional access and messaging capabilities. Pricing, billing, renewal, and cancellation are handled through the relevant app store."],
      ["Safety and moderation", "EliteLoop may limit, suspend, or remove accounts, content, or event activity where abuse, fraud, harassment, or safety risks are detected."],
      ["Changes to the service", "Features, design, and commercial plans may evolve over time. Continued use of the platform means accepting the latest published terms."]
    ],
    tr: [
      ["Platformu kullanmak", "EliteLoop'u kullanarak platformu hukuka uygun, saygılı ve rozet, etkinlik ve mesajlaşma kurallarıyla uyumlu şekilde kullanmayı kabul edersin."],
      ["Hesaplar ve erişim", "Kullanıcılar giriş bilgilerinden, hesap doğruluğundan ve uygulama içindeki aktivitelerinden sorumludur. Bazı özelliklere erişim rozet seviyesine veya etkinlik sahibinin onayına bağlıdır."],
      ["Etkinlikler ve katılım", "Etkinlik oluşturma, katılma, onaylama ve etkinlik etrafındaki mesajlaşma ürün kurallarına uygun olmalıdır. Etkinlik sahipleri ve katılımcılar iyi niyetli davranmalı ve sistemi kötüye kullanmamalıdır."],
      ["Abonelikler", "Ücretli planlar ek erişim ve mesajlaşma yetkileri açar. Fiyatlandırma, faturalama, yenileme ve iptal ilgili uygulama mağazası üzerinden yürür."],
      ["Güvenlik ve moderasyon", "EliteLoop, kötüye kullanım, dolandırıcılık, taciz veya güvenlik riski gördüğünde hesapları, içeriği veya etkinlik hareketlerini kısıtlayabilir, askıya alabilir ya da kaldırabilir."],
      ["Hizmette değişiklikler", "Özellikler, tasarım ve ticari planlar zamanla değişebilir. Platformu kullanmaya devam etmek yayınlanmış en güncel koşulları kabul ettiğin anlamına gelir."]
    ],
    ru: [
      ["Использование платформы", "Используя EliteLoop, вы соглашаетесь пользоваться платформой законно, уважительно и в соответствии с правилами о badge, событиях и сообщениях."],
      ["Аккаунты и доступ", "Пользователи отвечают за данные авторизации, точность аккаунта и активность внутри приложения. Доступ к части функций зависит от badge-уровня или одобрения хозяина."],
      ["События и участие", "Создание, участие, одобрение и переписка вокруг событий должны соответствовать правилам продукта. Хозяины и участники должны действовать добросовестно и не злоупотреблять системой."],
      ["Подписки", "Платные планы открывают дополнительный доступ и возможности переписки. Ценообразование, оплата, продление и отмена управляются через соответствующий магазин приложений."],
      ["Безопасность и модерация", "EliteLoop может ограничивать, приостанавливать или удалять аккаунты, контент или события при обнаружении злоупотребления, мошенничества, травли или рисков безопасности."],
      ["Изменения сервиса", "Функции, дизайн и коммерческие планы могут меняться со временем. Продолжение использования означает согласие с последней опубликованной версией условий."]
    ],
    ar: [
      ["استخدام المنصة", "باستخدام EliteLoop فإنك توافق على استخدام المنصة بشكل قانوني ومحترم ووفقا لقواعد المنتج المتعلقة بالشارات والفعاليات والرسائل."],
      ["الحسابات والوصول", "المستخدم مسؤول عن بيانات تسجيل الدخول وصحة الحساب ونشاطه داخل التطبيق. الوصول لبعض الميزات يعتمد على مستوى الشارة او موافقة صاحب الفعالية."],
      ["الفعاليات والمشاركة", "يجب ان يتوافق إنشاء الفعاليات والانضمام والموافقة والمراسلة المرتبطة بها مع قواعد المنتج. ويتوقع من المضيفين والمشاركين التصرف بحسن نية وعدم إساءة الاستخدام."],
      ["الاشتراكات", "تفتح الخطط المدفوعة مزايا وصول ومراسلة اضافية. وتتم ادارة التسعير والفوترة والتجديد والالغاء عبر متجر التطبيق المناسب."],
      ["السلامة والاشراف", "يجوز لـ EliteLoop تقييد الحسابات او المحتوى او النشاط او تعليقه او ازالته عند اكتشاف إساءة استخدام او احتيال او مضايقة او مخاطر تتعلق بالسلامة."],
      ["تغييرات الخدمة", "قد تتطور المزايا والتصميم والخطط التجارية مع الوقت. ويعني استمرار استخدام المنصة قبول احدث الشروط المنشورة."]
    ],
    zh: [
      ["使用平台", "使用 EliteLoop 即表示你同意以合法、尊重他人的方式使用平台，并遵守与徽章、活动和消息相关的产品规则。"],
      ["账户与访问", "用户需对自己的登录凭据、账户准确性以及应用内行为负责。部分功能的访问取决于徽章等级或主办方批准。"],
      ["活动与参与", "创建、加入、批准以及围绕活动的消息行为都必须遵守产品规则。活动主办方与参与者应善意使用平台，避免滥用。"],
      ["订阅", "付费方案会解锁额外访问与消息能力。价格、计费、续订与取消通过相应应用商店处理。"],
      ["安全与审核", "如发现滥用、欺诈、骚扰或安全风险，EliteLoop 可限制、暂停或移除账户、内容或活动行为。"],
      ["服务变更", "功能、设计与商业计划会随时间演进。持续使用平台意味着接受最新发布的条款。"]
    ],
    ja: [
      ["プラットフォームの利用", "EliteLoop を利用することで、バッジ、イベント、メッセージに関する製品ルールに沿って、合法的かつ敬意ある形で利用することに同意したものとみなされます。"],
      ["アカウントとアクセス", "ユーザーはログイン情報、アカウントの正確性、アプリ内での行動に責任を負います。一部の機能へのアクセスはバッジレベルや主催者の承認に依存します。"],
      ["イベントと参加", "イベントの作成、参加、承認、イベントに関連するメッセージは製品ルールに従う必要があります。主催者と参加者には誠実な行動と乱用の回避が求められます。"],
      ["サブスクリプション", "有料プランは追加のアクセス権とメッセージ機能を解放します。価格、請求、更新、解約は該当するアプリストアを通じて処理されます。"],
      ["安全とモデレーション", "乱用、詐欺、嫌がらせ、安全上のリスクが確認された場合、EliteLoop はアカウント、コンテンツ、イベント活動を制限、停止、削除できるものとします。"],
      ["サービス変更", "機能、デザイン、商用プランは時間とともに変化する場合があります。継続利用は最新の公開規約への同意を意味します。"]
    ]
  },
  gdpr: {
    en: [
      ["Data controller and contact", "EliteLoop acts as the controller for personal data processed in connection with the mobile product. Privacy-related requests can be sent to info@eliteloop.app."],
      ["Legal basis", "Processing may rely on consent, contractual necessity, legitimate interest, and legal obligations where relevant."],
      ["Your rights", "Depending on your jurisdiction, you may request access, correction, deletion, restriction, portability, objection, or withdrawal of consent."],
      ["Retention and deletion", "Personal data is retained for as long as it is needed for product operation, legal compliance, account management, and safety obligations. Deletion requests are handled through in-app and support flows."],
      ["International transfers", "Infrastructure and operational vendors may involve cross-border data handling. Appropriate safeguards should be maintained where required."],
      ["Security", "Technical and organizational protections should cover authentication, storage, transmission, and internal access control."]
    ],
    tr: [
      ["Veri sorumlusu ve iletişim", "EliteLoop, mobil ürünle bağlantılı işlenen kişisel veriler için veri sorumlusu olarak hareket eder. Gizlilik talepleri info@eliteloop.app adresine iletilebilir."],
      ["Hukuki dayanak", "Veri işleme; açık rıza, sözleşmesel gereklilik, meşru menfaat ve gerekli olduğu yerde yasal yükümlülüklere dayanabilir."],
      ["Haklarınız", "Bulunduğunuz yargı alanına göre erişim, düzeltme, silme, kısıtlama, taşınabilirlik, itiraz veya rızanın geri çekilmesini talep edebilirsiniz."],
      ["Saklama ve silme", "Kişisel veriler; ürün işleyişi, yasal uyum, hesap yönetimi ve güvenlik yükümlülükleri için gerektiği sürece tutulur. Silme talepleri uygulama içi ve destek akışlarıyla yönetilir."],
      ["Uluslararası aktarımlar", "Altyapı ve operasyon ortakları ülkeler arası veri işleme içerebilir. Gerekli olduğunda uygun güvenceler korunmalıdır."],
      ["Güvenlik", "Kimlik doğrulama, depolama, aktarım ve iç erişim kontrolünü kapsayan teknik ve organizasyonel korumalar uygulanmalıdır."]
    ],
    ru: [
      ["Контроллер данных и контакт", "EliteLoop выступает оператором персональных данных, обрабатываемых в связи с мобильным продуктом. Запросы по приватности можно отправлять на info@eliteloop.app."],
      ["Правовые основания", "Обработка может основываться на согласии, необходимости для договора, законных интересах и правовых обязательствах, где это применимо."],
      ["Ваши права", "В зависимости от юрисдикции вы можете запросить доступ, исправление, удаление, ограничение, переносимость, возражение или отзыв согласия."],
      ["Хранение и удаление", "Персональные данные хранятся столько, сколько это нужно для работы продукта, правового соответствия, управления аккаунтом и обязательств по безопасности. Запросы на удаление обрабатываются через приложение и поддержку."],
      ["Международные передачи", "Поставщики инфраструктуры и операционные партнёры могут участвовать в трансграничной обработке данных. При необходимости должны поддерживаться надлежащие гарантии."],
      ["Безопасность", "Технические и организационные меры должны закрывать авторизацию, хранение, передачу и внутренний контроль доступа."]
    ],
    ar: [
      ["المتحكم بالبيانات والتواصل", "يعمل EliteLoop كجهة متحكمة في البيانات الشخصية المعالجة فيما يتعلق بالمنتج المحمول. يمكن ارسال طلبات الخصوصية إلى info@eliteloop.app."],
      ["الاساس القانوني", "قد تستند المعالجة إلى الموافقة والضرورة التعاقدية والمصلحة المشروعة والالتزامات القانونية عند الاقتضاء."],
      ["حقوقك", "بحسب الولاية القانونية التي تتبع لها، يمكنك طلب الوصول أو التصحيح أو الحذف أو التقييد أو النقل أو الاعتراض أو سحب الموافقة."],
      ["الاحتفاظ والحذف", "تُحتفظ البيانات الشخصية طالما كانت مطلوبة لتشغيل المنتج والامتثال القانوني وإدارة الحساب والالتزامات المتعلقة بالسلامة. وتتم معالجة طلبات الحذف من خلال التطبيق والدعم."],
      ["النقل الدولي", "قد يشمل شركاء البنية التحتية والتشغيل معالجة عابرة للحدود. ويجب الحفاظ على الضمانات المناسبة عند الحاجة."],
      ["الامان", "يجب أن تغطي الحماية التقنية والتنظيمية المصادقة والتخزين والنقل والتحكم الداخلي بالوصول."]
    ],
    zh: [
      ["数据控制者与联系", "EliteLoop 作为与移动产品相关个人数据处理的数据控制者。隐私相关请求可发送至 info@eliteloop.app。"],
      ["法律依据", "数据处理可能基于同意、合同必要性、合法利益以及适用情况下的法定义务。"],
      ["你的权利", "根据你的法域，你可以请求访问、更正、删除、限制、可携带、反对，或撤回同意。"],
      ["保留与删除", "个人数据会在产品运行、法律合规、账户管理及安全义务所需期间内保留。删除请求通过应用内流程与支持渠道处理。"],
      ["国际传输", "基础设施与运营供应商可能涉及跨境数据处理。必要时应维持适当保障。"],
      ["安全", "技术与组织层面的保护应覆盖认证、存储、传输以及内部访问控制。"]
    ],
    ja: [
      ["データ管理者と連絡先", "EliteLoop はモバイル製品に関連して処理される個人データの管理者として機能します。プライバシーに関する依頼は info@eliteloop.app まで送信できます。"],
      ["法的根拠", "データ処理は、同意、契約上の必要性、正当な利益、必要な法的義務に基づく場合があります。"],
      ["あなたの権利", "法域によっては、アクセス、訂正、削除、制限、データポータビリティ、異議申立て、同意撤回を求めることができます。"],
      ["保持と削除", "個人データは、製品運用、法令遵守、アカウント管理、安全上の義務に必要な期間保持されます。削除依頼はアプリ内およびサポート経由で処理されます。"],
      ["国際移転", "インフラおよび運用ベンダーにより越境データ処理が行われる場合があります。必要に応じて適切な保護措置が維持されるべきです。"],
      ["セキュリティ", "認証、保存、送信、内部アクセス制御を含む技術的・組織的保護が適用されるべきです。"]
    ]
  },
  support: {
    en: [
      ["Support contact", "For support, account questions, subscription issues, or store review verification, you can reach EliteLoop at info@eliteloop.app."],
      ["Response scope", "The support surface should clearly help with login issues, subscriptions, badge access, messaging behavior, account flows, and privacy questions."],
      ["Recommended contact paths", "Users can reach support by email, through in-app settings when available, and through the legal pages linked from the website footer."],
      ["Store-readiness", "Keeping a clear support destination visible on the website helps App Store review, user trust, and operational consistency across iOS and Android."],
      ["What support covers", "EliteLoop support should cover technical problems, billing questions, account requests, moderation concerns, and privacy-related requests."],
      ["Primary address", "Email: info@eliteloop.app"]
    ],
    tr: [
      ["Destek iletişimi", "Destek, hesap soruları, abonelik problemleri veya store inceleme doğrulaması için EliteLoop'a info@eliteloop.app adresinden ulaşabilirsin."],
      ["Yanıt kapsamı", "Destek yüzeyi giriş sorunları, abonelikler, rozet erişimi, mesajlaşma davranışı, hesap akışları ve gizlilik soruları için net yardım vermelidir."],
      ["Önerilen iletişim yolları", "Kullanıcılar e-posta ile, varsa uygulama içi ayarlar üzerinden ve web sitesinin footer'ında bağlı olan yasal sayfalar üzerinden desteğe ulaşabilmelidir."],
      ["Store hazırlığı", "Web sitesinde net bir destek hedefinin görünür tutulması, App Store incelemesi, kullanıcı güveni ve iOS ile Android arasındaki operasyonel tutarlılık için faydalıdır."],
      ["Desteğin kapsadığı alanlar", "EliteLoop desteği teknik problemleri, faturalama sorularını, hesap taleplerini, moderasyon kaygılarını ve gizlilikle ilgili istekleri kapsamalıdır."],
      ["Birincil adres", "E-posta: info@eliteloop.app"]
    ],
    ru: [
      ["Контакт поддержки", "Для поддержки, вопросов по аккаунту, проблем с подпиской или проверки для store review можно написать EliteLoop на info@eliteloop.app."],
      ["Область помощи", "Поверхность поддержки должна ясно помогать с проблемами входа, подписок, badge-доступа, поведения сообщений, аккаунт-потоками и вопросами приватности."],
      ["Рекомендуемые каналы", "Пользователи должны иметь возможность обратиться в поддержку по email, через настройки в приложении, когда это доступно, и через правовые страницы из footer веб-сайта."],
      ["Готовность к сторам", "Ясный и видимый раздел поддержки на веб-сайте помогает проверке App Store, доверию пользователей и операционной последовательности между iOS и Android."],
      ["Что покрывает поддержка", "Поддержка EliteLoop должна покрывать технические проблемы, billing-вопросы, аккаунт-запросы, модерационные опасения и вопросы приватности."],
      ["Основной адрес", "Email: info@eliteloop.app"]
    ],
    ar: [
      ["التواصل مع الدعم", "للدعم، او اسئلة الحساب، او مشكلات الاشتراك، او التحقق الخاص بمراجعة المتجر، يمكنك التواصل مع EliteLoop عبر info@eliteloop.app."],
      ["نطاق الاستجابة", "يجب ان توضح واجهة الدعم المساعدة في مشاكل تسجيل الدخول، والاشتراكات، ووصول الشارات، وسلوك الرسائل، وتدفقات الحساب، واسئلة الخصوصية."],
      ["مسارات التواصل الموصى بها", "يجب ان يتمكن المستخدمون من الوصول الى الدعم عبر البريد الالكتروني، ومن داخل اعدادات التطبيق عند توفر ذلك، ومن خلال الصفحات القانونية المرتبطة في تذييل الموقع."],
      ["الجاهزية للمتاجر", "الحفاظ على وجهة دعم واضحة ومرئية على الموقع يساعد في مراجعة App Store ويزيد ثقة المستخدمين ويحافظ على الاتساق التشغيلي بين iOS وAndroid."],
      ["ما الذي يغطيه الدعم", "يجب ان يغطي دعم EliteLoop المشكلات التقنية، واسئلة الفوترة، وطلبات الحساب، ومخاوف الاشراف، والطلبات المتعلقة بالخصوصية."],
      ["العنوان الرئيسي", "البريد الالكتروني: info@eliteloop.app"]
    ],
    zh: [
      ["支持联系方式", "如需支持、账户问题、订阅问题或商店审核验证，你可以通过 info@eliteloop.app 联系 EliteLoop。"],
      ["支持范围", "支持页面应清晰覆盖登录问题、订阅、高级徽章访问、消息行为、账户流程以及隐私问题。"],
      ["推荐联系路径", "用户应能通过电子邮件、应用内设置（如可用）以及网站页脚中的法律页面入口联系支持。"],
      ["商店就绪性", "在网站上保持清晰可见的支持入口，有助于 App Store 审核、用户信任以及 iOS 与 Android 之间的运营一致性。"],
      ["支持涵盖内容", "EliteLoop 支持应覆盖技术问题、计费问题、账户请求、审核/举报问题以及隐私相关请求。"],
      ["主要地址", "邮箱：info@eliteloop.app"]
    ],
    ja: [
      ["サポート窓口", "サポート、アカウントに関する質問、サブスクリプションの問題、またはストア審査確認のために、EliteLoop には info@eliteloop.app で連絡できます。"],
      ["対応範囲", "サポート面では、ログイン問題、サブスクリプション、バッジアクセス、メッセージ動作、アカウント導線、プライバシーに関する質問を明確に扱うべきです。"],
      ["推奨される連絡経路", "ユーザーはメール、利用可能な場合はアプリ内設定、そしてサイトのフッターから辿れる法務ページ経由でサポートに連絡できるべきです。"],
      ["ストア審査の観点", "サイト上に明確で見えるサポート導線を置くことは、App Store 審査、ユーザーの信頼、iOS と Android 間の運用的一貫性に役立ちます。"],
      ["サポート対象", "EliteLoop のサポートは、技術的問題、課金の質問、アカウント依頼、モデレーション上の懸念、プライバシー関連の依頼を扱うべきです。"],
      ["主要連絡先", "メール: info@eliteloop.app"]
    ]
  },
  android: {
    en: [
      ["Platform intent", "Android is being rolled out with the same product standards, access logic, and premium presentation as iOS."],
      ["What stays aligned", "Badge rules, map-based discovery, event participation, messaging logic, privacy principles, and account behavior stay aligned across iOS and Android."],
      ["What adapts", "Android can use Google Maps, Android-safe marker rendering, safe-area aware bottom navigation, and keyboard-safe chat input while preserving the same product rules."],
      ["Why show this on the site", "If the website only says 'Download on App Store', users assume the brand only really lives on iPhone. A visible Android track fixes that perception."],
      ["Current rollout posture", "The Android story can be framed honestly as closed test, near-release, or rollout in motion while still looking polished and intentional."],
      ["Design direction", "The strongest landing version is one where Android is not visually secondary: it should sit near the main CTA and share the same premium narrative as iOS."]
    ],
    tr: [
      ["Platform niyeti", "Android, iPhone ürününün altına eklenmiş zayıf bir not gibi görünmemeli. Görsel dil onu da aynı derecede premium ve desteklenen bir hat gibi hissettirmeli."],
      ["Neler eşlenik kalır", "Rozet kuralları, harita tabanlı keşif, etkinlik katılımı, mesajlaşma mantığı, gizlilik ilkeleri ve hesap davranışı iOS ile Android arasında eşlenik kalır."],
      ["Neler uyarlanır", "Android; Google Maps, Android-güvenli marker render'ı, safe-area duyarlılığı olan alt menü ve klavye dostu chat input kullanabilir; ürün kuralları ise aynı kalır."],
      ["Bunu sitede neden gösterelim", "Eğer site sadece 'Download on App Store' diyorsa insanlar markanın gerçekten sadece iPhone'da yaşadığını düşünür. Görünür bir Android hattı bu algıyı düzeltir."],
      ["Mevcut rollout duruşu", "Android hikayesi dürüstçe kapalı test, çok yakın yayın ya da rollout halinde olarak anlatılabilir; yine de cilalı ve bilinçli görünebilir."],
      ["Tasarım yönü", "En güçlü landing versiyonu, Android'in görsel olarak ikinci planda kalmadığı versiyondur; ana CTA'nın yakınında durmalı ve iOS ile aynı premium hikâyeyi paylaşmalıdır."]
    ],
    ru: [
      ["Намерение платформы", "Android не должен выглядеть слабым дополнением под iPhone-продуктом. Визуальный язык должен делать его также premium и также поддерживаемым."],
      ["Что остаётся выровненным", "Badge-правила, обнаружение через карту, участие в событиях, логика сообщений, принципы приватности и поведение аккаунта остаются одинаковыми между iOS и Android."],
      ["Что адаптируется", "Android может использовать Google Maps, безопасный render маркеров, навигацию с учётом safe area и input чата, устойчивый к клавиатуре, сохраняя те же продуктовые правила."],
      ["Почему это надо показать на сайте", "Если сайт говорит только 'Download on App Store', люди думают, что бренд на самом деле живёт только на iPhone. Видимая Android-ветка исправляет это восприятие."],
      ["Текущая позиция rollout", "Android-историю можно честно подавать как закрытый тест, скоро выпуск или rollout в процессе, и при этом она всё равно может выглядеть отточенной и осмысленной."],
      ["Дизайнерское направление", "Самая сильная landing-версия — та, где Android не визуально вторичен: он должен стоять рядом с главным CTA и разделять тот же premium-нарратив, что и iOS."]
    ],
    ar: [
      ["نية المنصة", "يجب ألا يبدو Android وكأنه ملاحظة ضعيفة تحت منتج iPhone. يجب أن يجعل الخط البصري النسخة Android تبدو بنفس الدرجة من الفخامة والدعم."],
      ["ما الذي يبقى متوافقا", "تبقى قواعد الشارات، والاكتشاف عبر الخريطة، والمشاركة في الفعاليات، ومنطق الرسائل، ومبادئ الخصوصية، وسلوك الحساب متوافقة بين iOS وAndroid."],
      ["ما الذي يتكيف", "يمكن لـ Android استخدام Google Maps، وعرض العلامات بشكل آمن على Android، وتنقل سفلي يحترم safe area، وإدخال دردشة مناسب للوحة المفاتيح مع الحفاظ على القواعد نفسها."],
      ["لماذا نعرض هذا على الموقع", "إذا كان الموقع يقول فقط 'Download on App Store' فسيفترض الناس أن العلامة تعيش فعلا على iPhone فقط. وإظهار مسار Android يعالج هذا الانطباع."],
      ["وضع الإطلاق الحالي", "يمكن تقديم قصة Android بصدق كاختبار مغلق أو إطلاق قريب أو طرح جار مع الحفاظ على مظهر متقن ومقصود."],
      ["اتجاه التصميم", "أقوى نسخة من الصفحة هي التي لا يكون فيها Android ثانويا بصريا؛ يجب أن يقف قرب الدعوة الرئيسية وأن يشارك iOS السردية الفاخرة نفسها."]
    ],
    zh: [
      ["平台意图", "Android 不应看起来像 iPhone 产品下面的一条弱注释。视觉语言应让它同样高级、同样被认真支持。"],
      ["哪些部分保持一致", "徽章规则、地图发现、活动参与、消息逻辑、隐私原则与账户行为在 iOS 与 Android 之间保持一致。"],
      ["哪些部分进行适配", "Android 可以使用 Google Maps、Android 安全的标记渲染、考虑 safe area 的底部导航以及键盘安全的聊天输入，同时仍保持相同产品规则。"],
      ["为什么要在网站上展示", "如果网站只写 'Download on App Store'，用户会以为品牌真正只存在于 iPhone 上。可见的 Android 轨道能修正这种认知。"],
      ["当前发布姿态", "Android 的叙事可以诚实地表述为封闭测试、即将发布或持续 rollout，同时仍然看起来精致而有意图。"],
      ["设计方向", "最强的落地页版本是 Android 在视觉上不再是次要角色：它应站在主要 CTA 附近，并与 iOS 共享同样高级的品牌叙事。"]
    ],
    ja: [
      ["プラットフォームの意図", "Android は iPhone 製品の下に添えられた弱い注釈のように見えてはいけません。ビジュアル言語は Android も同じだけプレミアムで、同じだけ支えられていると感じさせるべきです。"],
      ["何が揃うのか", "バッジルール、地図ベースの発見、イベント参加、メッセージロジック、プライバシー原則、アカウント挙動は iOS と Android で揃えられます。"],
      ["何が適応されるのか", "Android では Google Maps、Android に安全なマーカーレンダリング、safe area に対応した下部ナビゲーション、キーボードに強いチャット入力を使いながら、同じ製品ルールを保てます。"],
      ["なぜサイトで見せるのか", "サイトが 'Download on App Store' だけを語ると、ブランドは本当は iPhone にしか存在しないと受け取られます。見える Android トラックはその印象を修正します。"],
      ["現在のローンチ姿勢", "Android の物語は、クローズドテスト、まもなく公開、ロールアウト中として正直に見せつつ、それでも磨かれた印象を保てます。"],
      ["デザインの方向性", "最も強いランディングは、Android が視覚的に二番手ではないものです。主 CTA の近くに置かれ、iOS と同じプレミアムな物語を共有すべきです。"]
    ]
  }
};

function getLang() {
  return localStorage.getItem("democodex-lang") || "en";
}

function setLang(lang) {
  localStorage.setItem("democodex-lang", lang);
}

function applyTranslations() {
  const lang = getLang();
  const dict = translations[lang] || translations.en;
  document.documentElement.lang = lang;
  document.body.classList.toggle("rtl", lang === "ar");

  document.querySelectorAll("[data-i18n]").forEach((node) => {
    const key = node.getAttribute("data-i18n");
    if (dict[key]) node.textContent = dict[key];
  });

  const langText = document.querySelector(".lang-text");
  if (langText) langText.textContent = lang.toUpperCase();

  document.querySelectorAll(".lang-option").forEach((button) => {
    button.classList.toggle("active", button.dataset.lang === lang);
  });
}

function renderLegalPage() {
  const page = document.body.dataset.page;
  const container = document.getElementById("legalContent");
  if (!container) return;
  const lang = getLang();

  if (page === "privacy" || page === "terms" || page === "gdpr" || page === "support") {
    const sections = legalContent[page][lang] || legalContent[page].en;
    container.innerHTML = sections.map(([title, body]) => `
      <article class="legal-section">
        <h2>${title}</h2>
        <p>${body}</p>
      </article>
    `).join("");
    return;
  }

  if (page === "android") {
    const sections = legalContent.android[lang] || legalContent.android.en;
    container.classList.add("android-grid");
    container.innerHTML = sections.map(([title, body]) => `
      <article class="android-card">
        <h2>${title}</h2>
        <p>${body}</p>
      </article>
    `).join("");
  }
}

function setupLanguageModal() {
  const modal = document.getElementById("langModal");
  const openBtn = document.getElementById("langBtn");
  const closeBtn = document.getElementById("closeLangModal");
  if (!modal || !openBtn || !closeBtn) return;

  openBtn.addEventListener("click", () => modal.classList.add("active"));
  closeBtn.addEventListener("click", () => modal.classList.remove("active"));
  modal.addEventListener("click", (event) => {
    if (event.target === modal) modal.classList.remove("active");
  });

  document.querySelectorAll(".lang-option").forEach((button) => {
    button.addEventListener("click", () => {
      setLang(button.dataset.lang);
      applyTranslations();
      renderLegalPage();
      modal.classList.remove("active");
    });
  });
}

applyTranslations();
renderLegalPage();
setupLanguageModal();
